platform :ios, '5.0'

pod 'RestKit', '~> 0.20.0'
pod 'JASidePanels','~> 1.3.0'
pod 'TTTAttributedLabel','~> 1.7.0'
pod 'SDWebImage','~> 3.3'
pod 'MBProgressHUD','~> 0.7'
pod 'AsyncImageView','~> 1.4.0'